#
# Spring Config
#

spring:
  application:
    name: simspro-service
    
server:
  port: 9001

#
#   Eureka Config
#


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/


